name: Daily Standup

on:
  schedule:
    # Runs every weekday (Monday to Friday) at 9 AM UTC
    - cron: '0 5 * * 1-5'
  workflow_dispatch: # Allows manual triggering

jobs:
  send-standup-prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Standup Issue
        uses: peter-evans/create-issue@v4
        with:
          title: "Daily Standup - ${{ github.event.schedule ? format('Today\'s Standup', '') : 'Manual Standup' }}"
          body: |
            **Daily Standup - ${{ github.event.schedule ? 'Scheduled' : 'Manual' }}**
            
            Please provide the following details:
            
            1. **Yesterday Tasks: -**
            2. **Today Tasks: -**
            3. **Impediments!**
            
            @here
          labels: 'Your Daily Standup'
